### ISSUE TITLE
Typo error in README.md

### ISSUE THREAD

**Issue by sridhareaswaran** [springer-opensource/omelet-example-dataset#1]
Typo error under description of "TestData_1.xml" in README.md.

Displayed as : 
mvn clean insatll -Denv-type=staging

**Comment by kapilag** [comment]
Thanks Sridharan ,actually this project is no longer maintained and the documentation as well is pretty old. Latest docs can be found over here and you can build sample project as well following 5 min tutorial on the website. 
http://springer-opensource.github.io/omelet/
